apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-calculator-deployment
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: online-calculator
  template:
    metadata:
      labels:
        app: online-calculator
    spec:
      containers:
      - name: online-calculator-container
        image: onlinecalculator:latest  
        ports:
        - containerPort: 8000  # FastAPI default port

