apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-calculator-deployment
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: online-calculator
  template:
    metadata:
      labels:
        app: online-calculator
    spec:
      containers:
      - name: online-calculator-container
        image: onlinecalculator:latest  # Replace with the actual image name
        ports:
        - containerPort: 8000  # FastAPI default port

---
apiVersion: v1
kind: Service
metadata:
  name: online-calculator-service
spec:
  selector:
    app: online-calculator
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 8000 # Container port
  type: NodePort  # Exposes the service outside the cluster (for Minikube)

